chat/urls.py
from django.urls import path, include
from . import views #chat, new_message_check, wink, chat_ajax, chat_home, read_messages, winks, read_wink, read_view, views, reject

urlpatterns = [
    path('home/', views.chat_home, name="chat_home"),
    path('<id>/', views.chat, name="chat"),
    path('wink/<id>', views.wink, name="wink"),
    path('winks/<id>', views.winks, name="winks"),
    path('views/<id>', views.views, name="views"),
]

dating_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('profiles.urls')),
    path('chat/', include('chat.urls')),
    path('search/', include('search.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.search, name="search"),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.expressions import RawSQL
import uuid
import datetime
import os

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, default='', blank=False)
    HAIR_COLOUR = (
        ('BLACK', 'Black'),
        ('BLONDE', 'Blonde'),
        ('BROWN', 'Brown'),
        ('RED', 'Red'),
        ('GREY', 'Grey'),
        ('BALD', 'Bald'),
        ('BLUE', 'Blue'),
        ('PINK', 'Pink'),
        ('GREEN', 'Green'),
        ('PURPLE', 'Purple'),
        ('OTHER', 'Other'),
    )
    BODY_TYPE = (
        ('THIN', 'Thin'),
        ('AVERAGE', 'Average'),
        ('FIT', 'Fit'),
        ('MUSCULAR', 'Muscular'),
        ('A LITTLE EXTRA', 'A Little Extra'),
        ('CURVY', 'Curvy'),
    )
    LOOKING_FOR = (
        ('MALE', 'Men'),
        ('FEMALE', 'Women'),
    )

    HAIR_LENGTH = (
        ('LONG', 'Long'),
        ('SHOULDER LENGTH', 'Shoulder Length'),
        ('AVERAGE', 'Average'),
        ('SHORT', 'Short'),
        ('SHAVED', 'Shaved')
    )
    ETHNICITY = (
        ('WHITE', 'White'),
        ('ASIAN: INDIAN', 'Asian: Indian'),
        ('ASIAN: PAKISTANI', 'Asian: Pakistani'),
        ('ASIAN: BANGLADESHI', 'Asian: Bangladeshi'),
        ('ASIAN: CHINESE', 'Asian: Chinese'),
        ('BLACK', 'Black'),
        ('MIXED', 'Mixed'),
        ('OTHER ETHNICITY', 'Other Ethnicity')
    )
    RELATIONSHIP_STATUS = (
        ('NEVER MARRIED', 'Never Married'),
        ('DIVORCED', 'Divorced'),
        ('WIDOWED', 'Widowed'),
        ('SEPARATED', 'Separated')
    )
    EDUCATION = (
    ('HIGH SCHOOL', 'High School'),
    ('COLLEGE', 'College'),
    ('BACHELORS DEGREE', 'Bachelors Degree'),
    ('MASTERS', 'Masters'),
    ('PHD / POST DOCTORAL', 'PhD / Post Doctoral'),
    )
    GENDER = (
        ("MALE", "Male"),
        ("FEMALE", "Female"))


    gender = models.CharField(choices=GENDER, default="Мужчина", max_length=7)
    hair_length = models.CharField(choices=HAIR_LENGTH, default="Длинные", blank=False, max_length=100)
    ethnicity = models.CharField(choices=ETHNICITY, default="Белый", blank=False, max_length=100)
    relationship_status = models.CharField(choices=RELATIONSHIP_STATUS, default="Не женат", blank=False, max_length=100)
    education = models.CharField(choices=EDUCATION, default="Среднее", blank=False, max_length=100)
    height = models.DecimalField(max_digits=10, default=170, decimal_places=0)
    hair_colour = models.CharField(choices=HAIR_COLOUR, default="Брюнет", blank=False, max_length=10)
    body_type = models.CharField(choices=BODY_TYPE, default="Худой", blank=False, max_length=15)
    looking_for = models.CharField(choices=LOOKING_FOR, default='Мужчина', blank=False, max_length=7)
    children = models.BooleanField(default=False)
    location = models.CharField(max_length=100, default='', blank=False)
    birth_date = models.DateField(null=True, default='1990-01-01', blank=True)

    def age(self):
        return int((datetime.date.today() - self.birth_date).days / 365.25  )

    def save(self, *args, **kwargs):
        # save the profile first
        super().save(*args, **kwargs)

def image_filename(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('media/', filename)

class ProfileImage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    image = models.ImageField(upload_to=image_filename, blank=True)

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.shortcuts import render
from profiles.models import Profile
from profiles.models import Profile
from .filters import ProfileFilter, GenderlessProfileFilter
from django.contrib.auth.decorators import login_required
from django.db import models
from django.db.models import Q, F
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Поиск людей по указанным фильтрам
@login_required
def search(request):
    min_height = request.GET.get('height_min')
    max_height = request.GET.get('height_max')

    user_gender = "MALE" if request.user.profile.gender == "MALE" else "FEMALE"
    qs = Profile.objects.filter(Q(looking_for=user_gender)).exclude(user_id=request.user.id)

    sexuality_query = Q()
    sexuality_query.add(~Q(looking_for=F('gender')), Q.AND)
    qs = qs.filter(sexuality_query)

    if min_height:
        qs = qs.filter(height__gte=min_height)
    if max_height:
        qs = qs.filter(height__lte=max_height)

    gender_check = "MALE" if request.user.profile.looking_for == "MALE" else "FEMALE"
    qs = qs.filter(gender=gender_check)
    filtered_result = GenderlessProfileFilter(request.GET, queryset=qs)

    search_paginated = Paginator(filtered_result.qs, 1)
    try:
        search_page = search_paginated.page(request.GET.get('page'))
    except PageNotAnInteger:
        search_page = search_paginated.page(1)
    except EmptyPage:
        search_page = search_paginated.page(search_paginated.num_pages)

    context = {
        'filtered_result': filtered_result,
        'search_page': search_page,
        'min_height': min_height,
        'max_height': max_height,
    }
    return render(request, 'search.html', context)

search/templates/search.html
{%extends 'base.html'%}
{% load static %}
{%block page_title%}Поиск{%endblock%}
{% block css %}
<link rel="stylesheet" href="{% static 'css/search.css' %}">
{% endblock %}
{%block content%}

<form class="first_section" method="GET">
  <div class="">
    Минимальный рост
    <br>
    <input {% if min_height %}data-min-height="{{min_height}}" {%endif%} title="Min Height" data-container="body" name="height_min"></input>
  </div>
  <div class="">
    Максимальный рост
    <br>
    <input {% if max_height %}data-max-height="{{max_height}}" {%endif%} title="Max Height" name="height_max"></input>
  </div>
  <div class="">
    Цвет волос
    {{ filtered_result.form.hair_colour }}
    <br>
  </div>
  <div class="">
    Длина волос
    {{ filtered_result.form.hair_length }}
    <br>
  </div>
  <div class="">
    Телосложение
    {{ filtered_result.form.body_type }}
    <br>
  </div>
  <div class="">
    Национальность
    {{ filtered_result.form.ethnicity }}
    <br>
  </div>
  <div class="">
    Отношения (статус)
    {{ filtered_result.form.relationship_status }}
    <br>
  </div>
  <div class="">
    Образование
    {{ filtered_result.form.education }}
    <br>
  </div>
  <br>
  <input class="butt" type="submit"></input>
  <a class="butt" href="{% url 'search' %}">Обновить</a>
</form>

<div class="second_section">
  {% if not search_page %}
  <p class="centered-text">Нет подходящих кандидатов. Попробуйте изменить фильтры.</p>
  {% endif %}
  {% for profile in search_page %}
    {% if profile.user.profileimage_set.first.image %}
    <div style="background-image: url( {{ MEDIA_URL }}{{profile.user.profileimage_set.first.image.url}});
      width: 380px;
      height: 380px;
      background-size: 100% 100%;" ></div>
    {% else %}
    <div style="  background-image: url({% static 'temp/profile-placeholder.png' %});
      width: 380px;
      height: 380px;
      background-size: 100% 100%;"></div>
    {% endif %}
    <p>Имя: {{profile.user.username}}</p>
    <p>Возраст: {{profile.age}}</p>
    <div class="search_buttons">
      <a href="{% url 'member_profile' profile.user.id %}" class="butt">Перейти в профиль</a>
      <a class="butt" href="{% url 'wink' profile.user.id %}">Подмигнуть</a>
    </div>
  {% endfor %}
</div>

<div class="paginator">
    {% if search_page %} {% for search in search_page %} {% endfor %} {% if search_page.has_previous %}
    <a href="?page={{ search_page.previous_page_number }}">Предыдущая</a>
    {% endif %}

    <span data-page={{page}} class="current">
    Страница {{ search_page.number }} из {{ search_page.paginator.num_pages }}
    </span>
    {% if search_page.has_next %}
    <a href="?page={{ search_page.next_page_number }}">Следующая ></a> {% endif %} {% endif %}
</div>
{% endblock %}